name: duo_tracker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_flavor: ^3.0.3
  flutter_flavorizr: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  sqflite: ^2.0.0+4
  enum_to_string: ^2.0.1
  google_mobile_ads: ^0.13.4
  admob_unit_ids: ^1.0.2
  shared_preferences: ^2.0.7
  http: ^0.13.3
  connectivity: ^3.0.6
  encrypt: ^5.0.1
  local_auth: ^1.1.7
  open_settings: ^2.0.2
  audioplayers: ^0.20.0
  flutter_html: ^2.1.2
  flutter_native_splash: ^1.2.3
  flutter_lints: ^1.0.4
  package_info: ^2.0.2
  launch_review: ^3.0.1
  share: ^2.0.4
  passcode_screen: ^2.0.0
  google_fonts: ^2.1.0
  clipboard: ^0.1.3
  flutter_speed_dial: ^4.3.0
  provider: ^6.0.0
  url_launcher: ^6.0.10
  awesome_dialog: ^2.1.1
  font_awesome_flutter: ^9.1.0
  dropdown_below: ^1.0.0
  tab_indicator_styler: ^2.0.0
  filter_list: ^1.0.0
  future_progress_dialog: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/duo_tracker_icon.png"

flutter_native_splash:
  image: "assets/icon/duo_tracker_icon.png"
  color: "00A1FF"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/bowie.png
    - assets/icon/bowie_license.png
    - assets/icon/mochi.png

flavorizr:
  app:
    android:
      flavorDimensions: "product_type"
    ios:

  flavors:
    free:
      app:
        name: "Duo Tracker"

      android:
        applicationId: "org.thinkit.free.duotracker"

      ios:
        bundleId: "org.thinkit.free.duotracker"

    paid:
      app:
        name: "Duo Tracker"

      android:
        applicationId: "org.thinkit.paid.duotracker"

      ios:
        bundleId: "org.thinkit.paid.duotracker"

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
